# Generated by Django 5.2.2 on 2025-12-29 03:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.CharField(choices=[('upholstered', 'Мягкая мебель'), ('case', 'Корпусная мебель'), ('office', 'Офисная мебель'), ('kitchen', 'Кухонная мебель')], default='case', max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип мебели',
                'verbose_name_plural': 'Типы мебели',
                'ordering': ('category', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя заказчика')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон заказчика')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('deadline', models.DateField(help_text='Планируемая дата завершения заказа', verbose_name='Срок выполнения')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата фактического выполнения')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая стоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('furniture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exhibits.furnituretype', verbose_name='Тип мебели')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/photos/', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='exhibits.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Фотография заказа',
                'verbose_name_plural': 'Фотографии заказа',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('workshop_number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер цеха')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_workshops', to=settings.AUTH_USER_MODEL, verbose_name='Начальник цеха')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
                'ordering': ('workshop_number',),
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата приема на работу')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='exhibits.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Рабочий',
                'verbose_name_plural': 'Рабочие',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='OrderWorkJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало работы')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Окончание работы')),
                ('work_description', models.TextField(blank=True, verbose_name='Описание выполненных работ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_journal', to='exhibits.order', verbose_name='Заказ')),
                ('workers', models.ManyToManyField(related_name='work_journal', to='exhibits.worker', verbose_name='Рабочие')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_journal', to='exhibits.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Запись журнала работы',
                'verbose_name_plural': 'Журнал работы',
                'ordering': ('-start_time',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='workshops',
            field=models.ManyToManyField(related_name='orders', to='exhibits.workshop', verbose_name='Цеха для выполнения'),
        ),
    ]
